use appvet;
ALTER TABLE apps DROP COLUMN updated;
ALTER TABLE apps ADD COLUMN lastupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER appid;
UPDATE apps SET lastupdated = NOW();
ALTER TABLE apps MODIFY submittime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users MODIFY lastlogon TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions DROP COLUMN expiretime;
ALTER TABLE sessions ADD COLUMN expiretime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP after clientaddress;
CREATE TABLE alerts (username VARCHAR(254) NOT NULL, time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, alerttype VARCHAR(64) NOT NULL DEFAULT 'NORMAL', message VARCHAR(1000) DEFAULT NULL);
