use appvet;
ALTER TABLE apps DROP COLUMN updated;
ALTER TABLE apps ADD COLUMN lastupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER appid;
UPDATE apps SET lastupdated = NOW();
ALTER TABLE apps MODIFY submittime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users MODIFY lastlogon TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions DROP COLUMN expiretime;
ALTER TABLE sessions ADD COLUMN expiretime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP after clientaddress;